package com.akashnavik.algo.dataList


//Sorting
var bubbleInfo = listOf<String>(
    "\"Bubble sort\" is one algorithm used to sort a sequence of numbers."
    ,"The Scales at the right end of the sequence will compare the number on their left and right side.",
    "In case ,they'll compare 7 and  6.",
    "After comparing them, if the number on the right is found to be smaller,the number will be swapped.",
    "6 is smaller than 7,so the number got swapped.",
    "After the comparison is finished,the scales move one position to the left.",
    "The number are compare once again.",
    "This time, 6 is greater than 4,so the number don't get swapped.",
    "The scales move one position to the left",
    "This operation is repeated until the scales reach the end of the sequence.",
    "This operation is repeated until the scales reach the end of the sequence.",
    "This operation is repeated until the scales reach the end of the sequence.",
    "This operation is repeated until the scales reach the end of the sequence.",
    "This operation is repeated until the scales reach the end of the sequence.",
    "This operation is repeated until the scales reach the end of the sequence.",
    "This operation is repeated until the scales reach the end of the sequence.",
    "The scales have reached the end of the sequence.",
    "In one Round of operations, the smallest value in the sequence is moved to the left edge.",
    "The number on the left edge is considered fully sorted..",
    "and the scales are moved back to thr right edge.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "Sorting is Compete.",
    "This concludes the explanation of bubble sort.",
)
var selectionInfo = listOf<String>("\"Selection sort\"is one algorithm used to sort a sequence of number",
    "Using a linear search, the smallest value in the sequence is located. A more detailed explanation of \"linear search\" can be found elsewhere in this app"
    ,"The smallest value swaps with the  leftmost number and is considered fully sorted.",
    "Furthermore ,if the smallest value happens to already be in the leftmost position, no operation is carried out.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "Sorting is Compete.",
    "This concludes the explanation of selection sort."

)
var insertionInfo = listOf<String>("\"Insertion sort\" is one algorithm used to sort a sequence of numbers of number"
    ,"To begin, the leftmost number is considered fully sorted.",
    "Next,from the remaining number the leftmost number is taken out...",
    "and compared to the already sorted number to its left.",
    "If the already sorted number is larger, the two number swap."
    ,"This operation repeats until either a number smaller appears, or the number reaches the left edge.",
    "In this case, 5 is greater than 3, so the number swap.",
    "The number reached the left edge, so the number stops moving.",
    "The 3 is now considered fully sorted.",
    "As before, the leftmost number from the remaining number is taken out..."
    ,"And compared to the number to its left.",
    "5 is greater than 4, so the number were swapped.",
    "3 is less than 4. A Smaller number has appeared, so the 4 stop moving.",
    "The 4 is now considered fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "The same operation are repeated until all of the number are fully sorted.",
    "All of the number are fully sorted, so sorting is complete.",
    "The concludes the explanation of insertion sort."

)
val heapInfo = listOf<String>(
    "\"Heap sort\" is one algorithm used to sort a sequence of numbers, and features the use of the heap data structure.",
    "To begin, all of the numbers are stored in a heap. These heaps are constructed so that numbers are in descending order. A more detailed explanation of heaps can be found in the \"Heaps\" entry of this app.",
    "To begin, all of the numbers are stored in a heap. These heaps are constructed so that numbers are in descending order. A more detailed explanation of heaps can be found in the \"Heaps\" entry of this app.",
    "To begin, all of the numbers are stored in a heap. These heaps are constructed so that numbers are in descending order. A more detailed explanation of heaps can be found in the \"Heaps\" entry of this app.",
    "To begin, all of the numbers are stored in a heap. These heaps are constructed so that numbers are in descending order. A more detailed explanation of heaps can be found in the \"Heaps\" entry of this app.",
    "To begin, all of the numbers are stored in a heap. These heaps are constructed so that numbers are in descending order. A more detailed explanation of heaps can be found in the \"Heaps\" entry of this app.",
    "To begin, all of the numbers are stored in a heap. These heaps are constructed so that numbers are in descending order. A more detailed explanation of heaps can be found in the \"Heaps\" entry of this app.",
    "To begin, all of the numbers are stored in a heap. These heaps are constructed so that numbers are in descending order. A more detailed explanation of heaps can be found in the \"Heaps\" entry of this app.",
    "To begin, all of the numbers are stored in a heap. These heaps are constructed so that numbers are in descending order. A more detailed explanation of heaps can be found in the \"Heaps\" entry of this app.",
    "To begin, all of the numbers are stored in a heap. These heaps are constructed so that numbers are in descending order. A more detailed explanation of heaps can be found in the \"Heaps\" entry of this app.",
    "To begin, all of the numbers are stored in a heap. These heaps are constructed so that numbers are in descending order. A more detailed explanation of heaps can be found in the \"Heaps\" entry of this app.",
    "To begin, all of the numbers are stored in a heap. These heaps are constructed so that numbers are in descending order. A more detailed explanation of heaps can be found in the \"Heaps\" entry of this app.",
    "To begin, all of the numbers are stored in a heap. These heaps are constructed so that numbers are in descending order. A more detailed explanation of heaps can be found in the \"Heaps\" entry of this app.",
    "All numbers have been stored in a heap.",
    "Next, the numbers stored in the heap are taken out one by one.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "One property of descending heaps is that numbers are removed from largest to smallest, so if you line the numbers up in the opposite order (right to left) as they get removed, sorting is complete.",
    "All of the numbers were removed from the heap, and sorting is complete."
)
val mergeInfo = listOf<String>(
    "\"Merge sort\" is one algorithm used to sort a sequence of numbers.",
    "First, the sequence is divided further and further into halves.",
    "First, the sequence is divided further and further into halves.",
    "First, the sequence is divided further and further into halves.",
    "First, the sequence is divided further and further into halves.",
    "The divisions are complete.",
    "Next, the divided groups are combined.",
    "When being combined, each group's numbers are arranged so that they're ordered from smallest to largest after combination.",
    "When being combined, each group's numbers are arranged so that they're ordered from smallest to largest after combination.",
    "When being combined, each group's numbers are arranged so that they're ordered from smallest to largest after combination.",
    "When groups with multiple numbers are combined, the first numbers are compared.",
    "In the diagram, first numbers 4 and 3 will be compared.",
    "4 is greater than 3, so the 3 is moved.",
    "The remaining rows have their first numbers compared in the same way.",
    "4 is less than 3, so the 4 is moved.",
    "6 is less than 7, so the 6 is moved.",
    "The remaining 7 is moved.",
    "The combining of groups is repeated recursively until all numbers form one group.",
    "The combining of groups is repeated recursively until all numbers form one group.",
    "The combining of groups is repeated recursively until all numbers form one group.",
    "The combining of groups is repeated recursively until all numbers form one group.",
    "The combining of groups is repeated recursively until all numbers form one group.",
    "Combining is complete, and the sequence has been sorted.",
    "This concludes the explanation of merge sort."
)
val quickInfo = listOf<String>(
    "Quicksort is one algorithm used to sort a sequence of numbers.",
    "One characteristic of quicksort is that it involves fewer comparisons and swaps than other algorithms, so it's able to sort quickly in many cases.",
    "Let's take a look at the algorithm in action.",
    "The first operation targets the entire sequence of numbers.",
    "A number is chosen as a reference for sorting. This number is called the \"pivot\".",
    "The pivot is normally a number chosen at random. This time, for convenience, the rightmost number will be chosen as the pivot.",
    "A marker will be placed on the pivot for easy reference.",
    "Next, a left marker will be placed on the leftmost number, and a right marker will be placed on the rightmost number.",
    "The quicksort algorithm uses these markers to repeatedly perform rounds of operations recursively.",
    "The left marker will move to the right.",
    "The left marker will move to the right.",
    "When the left marker reaches a number greater than or equal to the pivot number, it stops moving.",
    "In this case, 8 is greater than or equal to 6, so the marker stopped moving.",
    "Next, the right marker will move to the left.",
    "When the right marker reaches a number less than the pivot number, it stops.",
    "When the right marker reaches a number less than the pivot number, it stops.",
    "4 is less than 6, so the marker stopped moving.",
    "When both left and right markers have stopped, the markers' numbers are swapped.",
    "In this way, the left marker acts to find numbers greater than or equal to the pivot, and the right marker finds numbers less than the pivot.",
    "By swapping the numbers, you can gather numbers that are less than the pivot on the left side of the sequence, and numbers on the right side.",
    "After the swap, the left marker continues moving to the right.",
    "Like before, the left marker moves until it reaches a number greater than or equal to the pivot number.",
    "Like before, the left marker moves until it reaches a number greater than or equal to the pivot number.",
    "Like before, the left marker moves until it reaches a number greater than or equal to the pivot number.",
    "Like before, the left marker moves until it reaches a number greater than or equal to the pivot number.",
    "9 is greater than or equal to 6, so the marker stopped moving.",
    "Once again, the right marker is moved to the left.",
    "Once again, the right marker is moved to the left.",
    "Movement also stops when the right marker runs into the left marker.",
    "When both left and right markers stop and they're in the same position, that number is swapped with the pivot number.",
    "When both left and right markers stop and they're in the same position, that number is swapped with the pivot number.",
    "The number occupied by both the left and right markers is considered fully sorted.",
    "This completes the first round of operations.",
    "With one round of operations...",
    "we were able to put numbers smaller than the pivot to the left of the pivot...",
    "and numbers larger than the pivot to the right of the pivot.",
    "Another round of operations will be performed recursively on both sequences created by the division.",
    "Next, operations will be performed on the sequence to the left of the division.",
    "The 3 markers are placed.",
    "The same operation as before is performed.",
    "The same operation as before is performed.",
    "The same operation as before is performed.",
    "The same operation as before is performed.",
    "The same operation as before is performed.",
    "The same operation as before is performed.",
    "The same operation as before is performed.",
    "The same operation as before is performed.",
    "The same operation as before is performed.",
    "The same operation as before is performed.",
    "The same operation as before is performed.",
    "The round of operations is complete...",
    "and we were able to divide the sequence into numbers smaller than the pivot to the left of the pivot...",
    "and numbers larger than the pivot to the right of the pivot.",
    "Another round of operations is repeated recursively.",
    "The left side of the division will now undergo the operation.",
    "When the target sequence only has one number, it is considered fully sorted.",
    "When the target sequence only has one number, it is considered fully sorted.",
    "Now operations will be performed on the right side created by the 2nd round of operations.",
    "The 3 markers are placed.",
    "The left marker will move to the right.",
    "Even when the left marker runs into the right marker, it doesn't stop. It differs from the right marker in this respect.",
    "When the left marker reaches the rightmost edge of the target sequence, it stops.",
    "This means that the pivot number is the largest number in the target sequence.",
    "Next, the right marker would be moved, but when it has been passed by the left marker, it finishes without moving.",
    "When the left marker has reached the rightmost edge of the target sequence, the pivot number is considered fully sorted, and the round of operations ends.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "Hereafter, the same operations will be repeated until all of the numbers are fully sorted.",
    "All of the numbers have been fully sorted.",
    "This concludes the explanation of quicksort."
)
//List Search
val linearInfo = listOf<String>(
    "\"Linear Search\" is an algorithm for searching through elements of an array.",
    "Let's searching for the number 6.",
    "First, we examine the leftmost number in the array.",
    "We compare it with 6, and if it matches, the search ends. If it doesn't match, we examine the next number to the right.",
    "We repeat the comparisons until the 6 is found.",
    "We repeat the comparisons until the 6 is found.",
    "We repeat the comparisons until the 6 is found.",
    "We repeat the comparisons until the 6 is found.",
    "We repeat the comparisons until the 6 is found.",
    "We repeat the comparisons until the 6 is found.",
    "We found the 6, so the search is complete.",
    "As you can see, linear search is a simple technique for doing repeated comparisons in order from the beginning.",
    "When there's a lot of data, the number of comparisons increases, and it taken more time.",
    "This concludes the explanation of linear search."
)
val binaryInfo = listOf<String>(
    "\"Binary Search\" is an algorithm for searching through elements of an presorted array.",
    "Let's searching for the number 6.",
    "First, we look at the number in the center of the array. In this case it's 5.",
    "We compare 5 to the number 6 that we're searching for.Because 5 is less than 6, we know that the number 6 is to the right of 5.",
    "From the candidates, we remove number that are no longer needed.",
    "From the candidates, we remove number that are no longer needed.",
    "Again we look at the number in the center of the remaining array. This time it's 7.",
    "We compare 7 to the number 6. Because 6 is less than 7, we know that the number 6 is to the left of 7.",
    "From the candidates, we remove number that are no longer needed.",
    "From the candidates, we remove number that are no longer needed.",
    "We look at number in the center of the remaining array. This time it's 6",
    "6 = 6, so  we found the number we were looking for.",
    "In this way, we see that binary search  makes use of a presorted array and continuously halves the numbers to search through, allowing it to be very efficiently.",
    "The concludes the explanation of binary search."
    )